### ISSUE TITLE
Move this to an official (non-personal) public repository

### ISSUE THREAD

**Issue by MichaelNMaggs** [History-Research-Environment/HRE-the-history-of-everything#2]

**Comment by HREferg** [comment]
I've submitted a query to the GitHub folk as to who owns the 'other' HRE entry - waiting for a response

**Comment by sam-m888** [comment]
Had a [response](https://github.com/HREferg/HRE-the-history-of-everything/issues/1#issuecomment-293714476) off list from the owner and have sent invite to @HREferg

**Comment by johnathanmassey** [comment]
@sam-m888 I've removed myself from the organization, like I mentioned when I'm ready I'll join the project.

Good luck with the project everyone 👍

**Comment by HREferg** [comment]
Now transferred my private repo into here. Closing this issue.
